import type { Recipe } from './types'

export const STARTER_RECIPES: Recipe[] = [
  // ─── Zuurdesem ─────────────────────────────────────────────
  {
    id: 'zd-basis',
    name: 'Basis zuurdesembrood',
    category: 'Brood',
    subcategory: 'Zuurdesem',
    baseYield: 1,
    yieldUnit: 'brood',
    difficulty: 'Gemiddeld',
    prepTime: 1080,
    activeLaborMinutes: 10,
    suggestedPackagingCost: 0.05,
    photo: 'https://images.unsplash.com/photo-1597604391235-a7429b4b350c?w=600&q=80',
    description:
      'Een betrouwbaar wit zuurdesembrood met een krokante korst en zachte, luchtige kruim.',
    baseFlourGrams: 500,
    ingredients: [
      { id: 'zd1-1', name: 'Tarwebloem', quantity: 500, unit: 'gram', pricePerUnit: 1.20, bakerPercentage: 100 },
      { id: 'zd1-2', name: 'Water',       quantity: 350, unit: 'gram', pricePerUnit: 0,    bakerPercentage: 70 },
      { id: 'zd1-3', name: 'Zuurdesemstarter (100% hydr.)', quantity: 100, unit: 'gram', pricePerUnit: 0, bakerPercentage: 20, isStarter: true },
      { id: 'zd1-4', name: 'Zout',        quantity: 10,  unit: 'gram', pricePerUnit: 0.80, bakerPercentage: 2 },
    ],
    instructions: [
      'Meng bloem en 90% van het water en laat 30 tot 60 minuten rusten (autolyse).',
      'Voeg de zuurdesemstarter toe en meng goed.',
      'Voeg het zout en het resterende water toe.',
      'Doe 3 tot 4 stretch & folds tijdens de bulkrijs.',
      'Laat het deeg rijzen tot ongeveer 30 tot 50% volumetoename.',
      'Vorm het deeg strak op.',
      'Laat 2 tot 3 uur narijzen op kamertemperatuur óf 10 tot 14 uur in de koelkast.',
      'Bak 20 minuten op 250 °C met stoom of in een gesloten gietijzeren pan.',
      'Bak daarna 20 tot 25 minuten op 220 °C zonder stoom of zonder deksel.',
    ],
    fermentation:
      'Bulkrijs: 4–6 u op kamertemperatuur (22–24 °C) tot 30–50% volumetoename. Narijs: kort op kamertemp. of liefst 10–14 u koud (4 °C) voor diepere smaak.',
    baking: '20 min op 250 °C (met stoom/deksel) + 20–25 min op 220 °C (zonder stoom).',
  },
  {
    id: 'zd-rustiek',
    name: 'Rustiek zuurdesembrood',
    category: 'Brood',
    subcategory: 'Zuurdesem',
    baseYield: 1,
    yieldUnit: 'brood',
    difficulty: 'Gemiddeld',
    prepTime: 1140,
    activeLaborMinutes: 10,
    suggestedPackagingCost: 0.05,
    photo: 'https://images.unsplash.com/photo-1620921592619-652411a0d01a?w=600&q=80',
    description:
      'Een smaakvoller zuurdesembrood met volkorenmeel voor meer karakter en een stevigere kruim.',
    baseFlourGrams: 500,
    ingredients: [
      { id: 'zd2-1', name: 'Tarwebloem',   quantity: 400, unit: 'gram', pricePerUnit: 1.20, bakerPercentage: 80 },
      { id: 'zd2-2', name: 'Volkorenmeel', quantity: 100, unit: 'gram', pricePerUnit: 1.40, bakerPercentage: 20 },
      { id: 'zd2-3', name: 'Water',        quantity: 360, unit: 'gram', pricePerUnit: 0,    bakerPercentage: 72 },
      { id: 'zd2-4', name: 'Zuurdesemstarter (100% hydr.)', quantity: 100, unit: 'gram', pricePerUnit: 0, bakerPercentage: 20, isStarter: true },
      { id: 'zd2-5', name: 'Zout',         quantity: 10,  unit: 'gram', pricePerUnit: 0.80, bakerPercentage: 2 },
    ],
    instructions: [
      'Meng bloem, volkorenmeel en 90% van het water en laat 45 tot 60 minuten rusten.',
      'Voeg de zuurdesemstarter toe en meng goed.',
      'Voeg het zout en resterend water toe.',
      'Doe 3 tot 4 stretch & folds tijdens de bulkrijs.',
      'Laat het deeg 4 tot 6 uur fermenteren, afhankelijk van temperatuur.',
      'Vorm het deeg op.',
      'Laat koud narijzen voor extra smaak: 10 tot 14 uur in de koelkast.',
      'Bak 20 minuten op 250 °C met stoom of deksel.',
      'Bak daarna 25 minuten op 220 °C zonder stoom of deksel.',
    ],
    fermentation:
      'Bulkrijs: 4–6 u op 22–24 °C. Volkoren versnelt fermentatie — controleer op 30–50% volumetoename. Narijs: 10–14 u koud voor robuuste smaak.',
    baking: '20 min op 250 °C (met stoom/deksel) + 25 min op 220 °C (zonder stoom).',
  },
  {
    id: 'zd-high-hydration',
    name: 'Vochtrijk zuurdesembrood',
    category: 'Brood',
    subcategory: 'Zuurdesem',
    baseYield: 1,
    yieldUnit: 'brood',
    difficulty: 'Moeilijk',
    prepTime: 1200,
    activeLaborMinutes: 12,
    suggestedPackagingCost: 0.05,
    photo: 'https://images.unsplash.com/photo-1590301157172-7ba48dd1c2b2?w=600&q=80',
    description:
      'Een luchtig artisan zuurdesembrood met hogere hydratatie en een open kruim.',
    baseFlourGrams: 500,
    ingredients: [
      { id: 'zd3-1', name: 'Sterke tarwebloem', quantity: 500, unit: 'gram', pricePerUnit: 1.40, bakerPercentage: 100 },
      { id: 'zd3-2', name: 'Water',             quantity: 385, unit: 'gram', pricePerUnit: 0,    bakerPercentage: 77 },
      { id: 'zd3-3', name: 'Zuurdesemstarter (100% hydr.)', quantity: 100, unit: 'gram', pricePerUnit: 0, bakerPercentage: 20, isStarter: true },
      { id: 'zd3-4', name: 'Zout',              quantity: 10,  unit: 'gram', pricePerUnit: 0.80, bakerPercentage: 2 },
    ],
    instructions: [
      'Meng bloem en 90% van het water en laat 60 minuten rusten (autolyse).',
      'Voeg de starter toe en meng rustig.',
      'Voeg het zout en het resterende water toe.',
      'Werk met coil folds of stretch & folds, 4 tot 5 keer tijdens de bulkrijs.',
      'Laat het deeg rijzen tot 30 tot 50% volumetoename.',
      'Vorm voorzichtig op om lucht in het deeg te behouden.',
      'Laat 10 tot 14 uur narijzen in de koelkast.',
      'Bak 20 minuten op 250 °C met stoom of deksel.',
      'Bak daarna 20 tot 25 minuten op 220 °C zonder stoom of deksel.',
    ],
    fermentation:
      'Bulkrijs: 5–7 u op 22–24 °C met coil folds elke 30–45 min. Hogere hydratatie = voorzichtiger handelen. Narijs altijd koud (10–14 u).',
    baking: '20 min op 250 °C (met stoom/deksel) + 20–25 min op 220 °C (zonder stoom).',
  },
  // ─── Zoet gebak ────────────────────────────────────────────
  {
    id: 'cinnamon-rolls',
    name: 'Cinnamon Rolls',
    category: 'Zoet gebak',
    baseYield: 12,
    yieldUnit: 'stuks',
    difficulty: 'Gemiddeld',
    prepTime: 120,
    activeLaborMinutes: 60,
    suggestedPackagingCost: 0.1,
    photo: '/recipes/cinnamon-roll.jpg',
    ingredients: [
      { id: 'cr-1', name: 'Bloem', quantity: 500, unit: 'gram', pricePerUnit: 1.20 },
      { id: 'cr-2', name: 'Volle melk', quantity: 250, unit: 'ml', pricePerUnit: 1.10 },
      { id: 'cr-3', name: 'Boter', quantity: 80, unit: 'gram', pricePerUnit: 8.00 },
      { id: 'cr-4', name: 'Suiker', quantity: 60, unit: 'gram', pricePerUnit: 1.00 },
      { id: 'cr-5', name: 'Ei', quantity: 2, unit: 'stuk', pricePerUnit: 0.35 },
      { id: 'cr-6', name: 'Gist (gedroogd)', quantity: 7, unit: 'gram', pricePerUnit: 15.00 },
      { id: 'cr-11', name: 'Zout', quantity: 5, unit: 'gram', pricePerUnit: 0.80 },
      { id: 'cr-7', name: 'Kaneel', quantity: 10, unit: 'gram', pricePerUnit: 30.00 },
      { id: 'cr-8', name: 'Bruine suiker', quantity: 80, unit: 'gram', pricePerUnit: 1.50 },
      { id: 'cr-9', name: 'Boter (vulling)', quantity: 60, unit: 'gram', pricePerUnit: 8.00 },
      { id: 'cr-10', name: 'Poedersuiker', quantity: 100, unit: 'gram', pricePerUnit: 1.80 },
    ],
    description: 'Klassieke kaneelrolletjes met een rijk gistdeeg, romige glazuur en de lekkerste warm-uit-de-oven smaak.',
    instructions: [
      'Verwarm de melk lauw (ca. 35 °C) en los er de gist en suiker in op. Laat 10 minuten staan tot het schuimt.',
      'Meng de bloem en het zout in een grote kom. Voeg het ei, de zachte boter (80g) en het gistmengsel toe.',
      'Kneed 8-10 minuten tot het deeg soepel en elastisch is.',
      'Laat het deeg afgedekt 1 uur rijzen op een warme plek tot dubbele grootte.',
      'Rol uit tot een rechthoek van ongeveer 30×40 cm.',
      'Smeer met zachte boter (60g vulling), bestrooi met bruine suiker en kaneel.',
      'Rol strak op vanaf de lange zijde en snijd in 12 gelijke plakken.',
      'Leg in een ingevette bakvorm en laat 30-45 minuten narijzen.',
      'Bak 20-25 minuten op 180 °C tot goudbruin.',
      'Maak het glazuur met poedersuiker en een scheutje melk. Bedek de warme rolletjes vlak voor het serveren.',
    ],
    fermentation: 'Eerste rijs: 1 uur op kamertemperatuur (22-24 °C). Narijs in vorm: 30-45 min tot opgezwollen.',
    baking: '20-25 min op 180 °C tot goudbruin met zachte kern.',
  },
  // ─── Brood ─────────────────────────────────────────────────
  {
    id: 'koffiebroodjes',
    name: 'Koffiebroodjes',
    category: 'Brood',
    baseYield: 10,
    yieldUnit: 'stuks',
    difficulty: 'Gemiddeld',
    prepTime: 90,
    activeLaborMinutes: 45,
    suggestedPackagingCost: 0.08,
    photo: '/recipes/koffiebroodjes.jpg',
    ingredients: [
      { id: 'kb-1', name: 'Bloem', quantity: 450, unit: 'gram', pricePerUnit: 1.20 },
      { id: 'kb-2', name: 'Volle melk', quantity: 200, unit: 'ml', pricePerUnit: 1.10 },
      { id: 'kb-3', name: 'Boter', quantity: 100, unit: 'gram', pricePerUnit: 8.00 },
      { id: 'kb-4', name: 'Suiker', quantity: 50, unit: 'gram', pricePerUnit: 1.00 },
      { id: 'kb-5', name: 'Ei', quantity: 2, unit: 'stuk', pricePerUnit: 0.35 },
      { id: 'kb-6', name: 'Gist (gedroogd)', quantity: 7, unit: 'gram', pricePerUnit: 15.00 },
      { id: 'kb-7', name: 'Zout', quantity: 5, unit: 'gram', pricePerUnit: 0.80 },
      { id: 'kb-8', name: 'Rozijnen', quantity: 100, unit: 'gram', pricePerUnit: 6.00 },
      { id: 'kb-9', name: 'Ei (voor bestrijken)', quantity: 1, unit: 'stuk', pricePerUnit: 0.35 },
    ],
    description: 'Zachte zoete broodjes met rozijnen — perfect bij koffie of als ontbijt.',
    instructions: [
      'Verwarm de melk lauw en meng met de gist en suiker. Laat 10 minuten activeren.',
      'Meng de bloem en het zout in een kom. Voeg het gistmengsel, ei en zachte boter toe.',
      'Kneed 8-10 minuten tot een soepel deeg.',
      'Was de rozijnen, dep droog en kneed door het deeg.',
      'Laat afgedekt 1 uur rijzen op een warme plek.',
      'Verdeel in 10 gelijke stukken en vorm strakke bolletjes.',
      'Druk plat tot ovaalvorm en leg op een bakplaat met bakpapier.',
      'Laat 30-40 minuten narijzen tot opgezwollen.',
      'Bestrijk met losgeklopt ei.',
      'Bak 18-20 minuten op 180 °C tot goudbruin.',
    ],
    fermentation: 'Bulk: 60 min op 22-24 °C. Narijs: 30-40 min.',
    baking: '18-20 min op 180 °C.',
  },
  // ─── Cake ──────────────────────────────────────────────────
  {
    id: 'cake',
    name: 'Cake',
    category: 'Cake',
    baseYield: 12,
    yieldUnit: 'plakjes',
    difficulty: 'Makkelijk',
    prepTime: 60,
    activeLaborMinutes: 15,
    suggestedPackagingCost: 0.2,
    photo: '/recipes/cake.jpg',
    ingredients: [
      { id: 'vc-1', name: 'Bloem', quantity: 250, unit: 'gram', pricePerUnit: 1.20 },
      { id: 'vc-2', name: 'Boter', quantity: 200, unit: 'gram', pricePerUnit: 8.00 },
      { id: 'vc-3', name: 'Suiker', quantity: 200, unit: 'gram', pricePerUnit: 1.00 },
      { id: 'vc-4', name: 'Ei', quantity: 4, unit: 'stuk', pricePerUnit: 0.35 },
      { id: 'vc-5', name: 'Vanille-extract', quantity: 5, unit: 'ml', pricePerUnit: 80.00 },
      { id: 'vc-6', name: 'Bakpoeder', quantity: 8, unit: 'gram', pricePerUnit: 10.00 },
      { id: 'vc-7', name: 'Melk', quantity: 60, unit: 'ml', pricePerUnit: 1.10 },
      { id: 'vc-8', name: 'Zout', quantity: 3, unit: 'gram', pricePerUnit: 0.80 },
    ],
    description: 'Klassieke vanille cake — luchtig, boterig en eenvoudig.',
    instructions: [
      'Verwarm de oven voor op 170 °C en bekleed een cakevorm met bakpapier.',
      'Klop de zachte boter met de suiker romig en bleek (ca. 5 minuten).',
      'Voeg de eieren één voor één toe en blijf goed kloppen tussen elke toevoeging.',
      'Roer de vanille-extract erdoor.',
      'Zeef bloem, bakpoeder en zout boven de kom en spatel beetje bij beetje door het beslag.',
      'Voeg de melk toe en spatel tot een glad beslag (niet overmixen).',
      'Stort het beslag in de cakevorm en strijk glad.',
      'Bak 50-60 minuten tot een prikker er schoon uitkomt.',
      'Laat 10 minuten afkoelen in de vorm, daarna op een rooster verder afkoelen.',
    ],
    baking: '50-60 min op 170 °C, prikker-test: schoon = klaar.',
  },
  // ─── Koekjes ───────────────────────────────────────────────
  {
    id: 'gevulde-koek',
    name: 'Gevulde koek',
    category: 'Koekjes',
    baseYield: 12,
    yieldUnit: 'stuks',
    difficulty: 'Gemiddeld',
    prepTime: 75,
    activeLaborMinutes: 45,
    suggestedPackagingCost: 0.08,
    photo: '/recipes/gevulde-koek.jpeg',
    description:
      'Klassieke Hollandse gevulde koeken met amandelspijs en een hele amandel als decoratie.',
    ingredients: [
      { id: 'gk-1', name: 'Bloem', quantity: 250, unit: 'gram', pricePerUnit: 1.20 },
      { id: 'gk-2', name: 'Roomboter (koud)', quantity: 175, unit: 'gram', pricePerUnit: 8.50 },
      { id: 'gk-3', name: 'Suiker', quantity: 125, unit: 'gram', pricePerUnit: 1.00 },
      { id: 'gk-4', name: 'Ei (in deeg)', quantity: 1, unit: 'stuk', pricePerUnit: 0.35 },
      { id: 'gk-5', name: 'Snufje zout', quantity: 2, unit: 'gram', pricePerUnit: 0.80 },
      { id: 'gk-6', name: 'Citroenrasp', quantity: 1, unit: 'stuk', pricePerUnit: 0.40 },
      { id: 'gk-7', name: 'Amandelspijs', quantity: 250, unit: 'gram', pricePerUnit: 12.00 },
      { id: 'gk-8', name: 'Ei (voor bestrijken)', quantity: 1, unit: 'stuk', pricePerUnit: 0.35 },
      { id: 'gk-9', name: 'Hele amandelen', quantity: 12, unit: 'stuk', pricePerUnit: 0.10 },
    ],
    instructions: [
      'Meng bloem, suiker, snufje zout en citroenrasp in een kom.',
      'Voeg de koude boter in blokjes en het ei toe. Kneed snel tot een samenhangend deeg.',
      'Verpak in folie en laat minstens 30 minuten rusten in de koelkast.',
      'Verwarm de oven voor op 175 °C.',
      'Verdeel het deeg in 24 gelijke stukken (12 onderkanten + 12 deksels).',
      'Rol elk stukje uit tot een rondje van ongeveer 8 cm.',
      'Verdeel een bolletje amandelspijs (ca. 20 g) op elke onderkant.',
      'Plaats een bovenkant erop en druk de randen voorzichtig dicht.',
      'Bestrijk met losgeklopt ei en druk een hele amandel in het midden.',
      'Bak 20-25 minuten op 175 °C tot goudbruin.',
    ],
    baking: '20-25 min op 175 °C tot goudbruin.',
  },
  // ─── Taart ─────────────────────────────────────────────────
  {
    id: 'appeltaart',
    name: 'Appeltaart',
    category: 'Cake',
    baseYield: 8,
    yieldUnit: 'plakjes',
    difficulty: 'Gemiddeld',
    prepTime: 90,
    activeLaborMinutes: 45,
    suggestedPackagingCost: 0.30,
    photo: '/recipes/appeltaart.jpg',
    description:
      'Klassieke Hollandse appeltaart met kaneel, rozijnen en een knapperig korstdeeg.',
    ingredients: [
      { id: 'at-1', name: 'Bloem', quantity: 300, unit: 'gram', pricePerUnit: 1.20 },
      { id: 'at-2', name: 'Roomboter (koud)', quantity: 200, unit: 'gram', pricePerUnit: 8.50 },
      { id: 'at-3', name: 'Bruine basterdsuiker (deeg)', quantity: 125, unit: 'gram', pricePerUnit: 1.60 },
      { id: 'at-4', name: 'Ei (in deeg)', quantity: 1, unit: 'stuk', pricePerUnit: 0.35 },
      { id: 'at-5', name: 'Citroenrasp', quantity: 1, unit: 'stuk', pricePerUnit: 0.40 },
      { id: 'at-6', name: 'Snufje zout', quantity: 2, unit: 'gram', pricePerUnit: 0.80 },
      { id: 'at-7', name: 'Goudreinetten of Elstar', quantity: 1000, unit: 'gram', pricePerUnit: 2.50 },
      { id: 'at-12', name: 'Bruine basterdsuiker (vulling)', quantity: 50, unit: 'gram', pricePerUnit: 1.60 },
      { id: 'at-8', name: 'Kaneel (deeg)', quantity: 4, unit: 'gram', pricePerUnit: 30.00 },
      { id: 'at-13', name: 'Kaneel (vulling)', quantity: 4, unit: 'gram', pricePerUnit: 30.00 },
      { id: 'at-9', name: 'Rozijnen', quantity: 75, unit: 'gram', pricePerUnit: 6.00 },
      { id: 'at-10', name: 'Paneermeel', quantity: 30, unit: 'gram', pricePerUnit: 2.50 },
      { id: 'at-11', name: 'Ei (voor bestrijken)', quantity: 1, unit: 'stuk', pricePerUnit: 0.35 },
    ],
    instructions: [
      'Meng de bloem, basterdsuiker (deeg, 125g), kaneel (deeg, 4g), citroenrasp en zout.',
      'Voeg de koude boter in blokjes en het ei toe. Kneed kort tot een samenhangend deeg.',
      'Verpak in folie en laat 30 minuten rusten in de koelkast.',
      'Schil de appels, snijd in partjes en mix met de rozijnen, basterdsuiker (vulling, 50g) en kaneel (vulling, 4g).',
      'Vet een springvorm (24 cm) in en bekleed met 2/3 van het deeg (bodem + zijkant ca. 5 cm).',
      'Strooi het paneermeel op de bodem — dit vangt het appelsap op.',
      'Vul stevig met het appelmengsel.',
      'Rol de rest van het deeg uit en snijd strookjes voor het ruitenpatroon.',
      'Bestrijk de strookjes met losgeklopt ei.',
      'Bak 60-70 minuten op 180 °C tot goudbruin.',
      'Laat volledig afkoelen vóór het aansnijden — dit voorkomt dat de vulling uitloopt.',
    ],
    baking: '60-70 min op 180 °C. Volledig laten afkoelen.',
  },
  {
    id: 'vruchtentaart',
    name: 'Vruchtentaart',
    category: 'Cake',
    baseYield: 8,
    yieldUnit: 'plakjes',
    difficulty: 'Gemiddeld',
    prepTime: 75,
    activeLaborMinutes: 50,
    suggestedPackagingCost: 0.30,
    photo: '/recipes/vruchtentaart.jpg',
    description:
      'Frisse vruchtentaart met biscuitbodem, banketbakkersroom en seizoensfruit.',
    ingredients: [
      { id: 'vt-1', name: 'Bloem (biscuit)', quantity: 100, unit: 'gram', pricePerUnit: 1.20 },
      { id: 'vt-2', name: 'Suiker (biscuit)', quantity: 100, unit: 'gram', pricePerUnit: 1.00 },
      { id: 'vt-3', name: 'Ei (biscuit)', quantity: 4, unit: 'stuk', pricePerUnit: 0.35 },
      { id: 'vt-4', name: 'Vanille-extract', quantity: 5, unit: 'ml', pricePerUnit: 80.00 },
      { id: 'vt-5', name: 'Volle melk (room)', quantity: 500, unit: 'ml', pricePerUnit: 1.10 },
      { id: 'vt-6', name: 'Eidooier (room)', quantity: 4, unit: 'stuk', pricePerUnit: 0.35 },
      { id: 'vt-7', name: 'Suiker (room)', quantity: 100, unit: 'gram', pricePerUnit: 1.00 },
      { id: 'vt-8', name: 'Maizena', quantity: 40, unit: 'gram', pricePerUnit: 3.00 },
      { id: 'vt-9', name: 'Vers fruit (mix)', quantity: 400, unit: 'gram', pricePerUnit: 8.00 },
      { id: 'vt-10', name: 'Abrikozenjam (glazuur)', quantity: 80, unit: 'gram', pricePerUnit: 4.50 },
    ],
    instructions: [
      'BISCUIT: klop de eieren met de suiker 8-10 minuten luchtig (lint-stadium).',
      'Roer de vanille-extract erdoor en zeef de bloem boven de kom.',
      'Spatel voorzichtig door (verlies geen lucht) en stort in een ingevette springvorm (24 cm).',
      'Bak 20-25 minuten op 180 °C tot lichtgoud en veerkrachtig.',
      'Laat volledig afkoelen.',
      'BANKETBAKKERSROOM: verwarm de melk in een steelpan tot tegen het kookpunt.',
      'Klop dooiers met suiker en maizena tot bleek en luchtig.',
      'Giet de warme melk al kloppend bij het dooier-mengsel.',
      'Terug in de pan en blijf roeren op middelhoog vuur tot de room bindt (3-5 min).',
      'Stort in een schaal, dek af met folie op de room (geen velvorming) en koel.',
      'AFBOUW: snijd de biscuit in 2 lagen. Vul met de afgekoelde room en plaats de bovenkant terug.',
      'Beleg royaal met vers fruit in een mooi patroon.',
      'Verwarm de abrikozenjam met een scheutje water en kwast over het fruit voor glans.',
      'Koel minimaal 1 uur voor het serveren.',
    ],
    baking: 'Biscuit: 20-25 min op 180 °C.',
  },
  // ─── Brood (extra) ─────────────────────────────────────────
  {
    id: 'krentenbollen',
    name: 'Krentenbollen',
    category: 'Brood',
    baseYield: 12,
    yieldUnit: 'stuks',
    difficulty: 'Makkelijk',
    prepTime: 90,
    activeLaborMinutes: 35,
    suggestedPackagingCost: 0.05,
    photo: '/recipes/krentenbollen.jpg',
    description:
      'Zachte zoete bollen rijkelijk gevuld met krenten en rozijnen.',
    ingredients: [
      { id: 'kr-1', name: 'Bloem', quantity: 500, unit: 'gram', pricePerUnit: 1.20 },
      { id: 'kr-2', name: 'Volle melk', quantity: 250, unit: 'ml', pricePerUnit: 1.10 },
      { id: 'kr-3', name: 'Boter', quantity: 60, unit: 'gram', pricePerUnit: 8.00 },
      { id: 'kr-4', name: 'Suiker', quantity: 60, unit: 'gram', pricePerUnit: 1.00 },
      { id: 'kr-5', name: 'Ei (in deeg)', quantity: 1, unit: 'stuk', pricePerUnit: 0.35 },
      { id: 'kr-6', name: 'Gist (gedroogd)', quantity: 7, unit: 'gram', pricePerUnit: 15.00 },
      { id: 'kr-7', name: 'Zout', quantity: 8, unit: 'gram', pricePerUnit: 0.80 },
      { id: 'kr-8', name: 'Krenten', quantity: 150, unit: 'gram', pricePerUnit: 7.00 },
      { id: 'kr-9', name: 'Rozijnen', quantity: 100, unit: 'gram', pricePerUnit: 6.00 },
      { id: 'kr-10', name: 'Ei (voor bestrijken)', quantity: 1, unit: 'stuk', pricePerUnit: 0.35 },
    ],
    instructions: [
      'Verwarm de melk lauw en meng met de gist en suiker. Laat 10 min activeren.',
      'Meng bloem en zout in een kom. Voeg gistmengsel, ei en zachte boter toe.',
      'Kneed 8-10 minuten tot een soepel deeg.',
      'Was de krenten en rozijnen, dep droog en kneed door het deeg.',
      'Laat afgedekt 1 uur rijzen op een warme plek tot dubbele grootte.',
      'Verdeel in 12 gelijke stukken en vorm strakke bolletjes.',
      'Leg op een bakplaat met bakpapier en laat 30-40 minuten narijzen.',
      'Bestrijk met losgeklopt ei.',
      'Bak 18-20 minuten op 200 °C tot goudbruin.',
    ],
    fermentation: 'Bulk: 60 min op 22-24 °C. Narijs: 30-40 min.',
    baking: '18-20 min op 200 °C.',
  },
  {
    id: 'croissants',
    name: 'Croissants',
    category: 'Brood',
    baseYield: 12,
    yieldUnit: 'stuks',
    difficulty: 'Moeilijk',
    prepTime: 720,
    activeLaborMinutes: 90,
    suggestedPackagingCost: 0.10,
    photo: '/recipes/croissants.jpg',
    description:
      'Boterachtige laagjes croissants — vraagt geduld en koude boter, maar het resultaat is bakkerijwaardig.',
    ingredients: [
      { id: 'cs-1', name: 'Bloem', quantity: 500, unit: 'gram', pricePerUnit: 1.20 },
      { id: 'cs-2', name: 'Volle melk', quantity: 220, unit: 'ml', pricePerUnit: 1.10 },
      { id: 'cs-3', name: 'Boter (in deeg)', quantity: 50, unit: 'gram', pricePerUnit: 8.50 },
      { id: 'cs-4', name: 'Suiker', quantity: 55, unit: 'gram', pricePerUnit: 1.00 },
      { id: 'cs-5', name: 'Gist (gedroogd)', quantity: 7, unit: 'gram', pricePerUnit: 15.00 },
      { id: 'cs-6', name: 'Zout', quantity: 10, unit: 'gram', pricePerUnit: 0.80 },
      { id: 'cs-7', name: 'Roomboter (toerenbeslag)', quantity: 250, unit: 'gram', pricePerUnit: 8.50 },
      { id: 'cs-8', name: 'Ei (voor bestrijken)', quantity: 1, unit: 'stuk', pricePerUnit: 0.35 },
    ],
    instructions: [
      'Meng bloem, suiker, zout, gist en de zachte boter (50 g) in een kom.',
      'Voeg melk toe en kneed tot een soepel deeg. Laat 1 uur rijzen op kamertemperatuur.',
      'Plat het deeg af tot rechthoek, verpak in folie en leg 1 uur in de koelkast.',
      'Vorm de toerenboter (250 g) in een vierkant van 20×20 cm tussen 2 vellen folie. Houd koud.',
      'Rol het deeg uit tot een rechthoek van 40×20 cm. Leg de boter in het midden.',
      'Vouw de zijkanten over de boter (eerste toer = enveloppe).',
      'Rol uit tot rechthoek en geef een drievoudige toer. Koel 30 minuten.',
      'Herhaal de drievoudige toer nog 2 keer met telkens 30 minuten koelen ertussen (totaal 3 toeren).',
      'Rol uit tot een grote rechthoek en snijd 12 gelijke driehoeken (basis ca. 9 cm, hoogte ca. 24 cm).',
      'Rol elk driehoek op vanaf de brede kant naar de punt en plaats op een bakplaat.',
      'Laat 2 uur narijzen op kamertemperatuur.',
      'Bestrijk met losgeklopt ei.',
      'Bak 15-18 minuten op 200 °C tot goudbruin en knapperig.',
    ],
    fermentation: 'Eerste rijs: 1 u op kamertemp. Tussendoor 30 min koeling per toer. Narijs: 2 u op kamertemp.',
    baking: '15-18 min op 200 °C.',
  },
  {
    id: 'luxe-broodjes',
    name: 'Luxe broodjes',
    category: 'Brood',
    baseYield: 12,
    yieldUnit: 'stuks',
    difficulty: 'Makkelijk',
    prepTime: 90,
    activeLaborMinutes: 35,
    suggestedPackagingCost: 0.06,
    photo: '/recipes/luxe-broodjes.jpg',
    description:
      'Zachte, rijke broodjes met boter en ei — perfect voor brunch of zondagochtend.',
    ingredients: [
      { id: 'lb-1', name: 'Bloem', quantity: 500, unit: 'gram', pricePerUnit: 1.20 },
      { id: 'lb-2', name: 'Volle melk', quantity: 250, unit: 'ml', pricePerUnit: 1.10 },
      { id: 'lb-3', name: 'Boter', quantity: 80, unit: 'gram', pricePerUnit: 8.00 },
      { id: 'lb-4', name: 'Suiker', quantity: 50, unit: 'gram', pricePerUnit: 1.00 },
      { id: 'lb-5', name: 'Ei (in deeg)', quantity: 2, unit: 'stuk', pricePerUnit: 0.35 },
      { id: 'lb-6', name: 'Gist (gedroogd)', quantity: 7, unit: 'gram', pricePerUnit: 15.00 },
      { id: 'lb-7', name: 'Zout', quantity: 8, unit: 'gram', pricePerUnit: 0.80 },
      { id: 'lb-8', name: 'Ei (voor bestrijken)', quantity: 1, unit: 'stuk', pricePerUnit: 0.35 },
    ],
    instructions: [
      'Verwarm de melk lauw en meng met de gist en suiker. Laat 10 min activeren.',
      'Meng bloem en zout in een grote kom.',
      'Voeg het gistmengsel, eieren en zachte boter toe.',
      'Kneed 10 minuten tot een soepel, elastisch deeg.',
      'Laat 1 uur rijzen op een warme plek tot dubbele grootte.',
      'Verdeel in 12 gelijke stukken en vorm strakke bolletjes.',
      'Leg op een bakplaat met bakpapier (op afstand van elkaar).',
      'Laat 30-45 minuten narijzen.',
      'Bestrijk met losgeklopt ei.',
      'Bak 15-18 minuten op 200 °C tot goudbruin.',
    ],
    fermentation: 'Bulk: 60 min op 22-24 °C. Narijs: 30-45 min.',
    baking: '15-18 min op 200 °C.',
  },
]
