import type { Recipe } from './types'

export const STARTER_RECIPES: Recipe[] = [
  // ─── Zuurdesem ─────────────────────────────────────────────
  {
    id: 'zd-basis',
    name: 'Basis zuurdesembrood',
    category: 'Brood',
    subcategory: 'Zuurdesem',
    baseYield: 1,
    yieldUnit: 'brood',
    difficulty: 'Gemiddeld',
    prepTime: 1080,
    activeLaborMinutes: 10,
    suggestedPackagingCost: 0.05,
    photo: 'https://images.unsplash.com/photo-1597604391235-a7429b4b350c?w=600&q=80',
    description:
      'Een betrouwbaar wit zuurdesembrood met een krokante korst en zachte, luchtige kruim.',
    baseFlourGrams: 500,
    ingredients: [
      { id: 'zd1-1', name: 'Tarwebloem', quantity: 500, unit: 'gram', pricePerUnit: 1.20, bakerPercentage: 100 },
      { id: 'zd1-2', name: 'Water',       quantity: 350, unit: 'gram', pricePerUnit: 0,    bakerPercentage: 70 },
      { id: 'zd1-3', name: 'Zuurdesemstarter (100% hydr.)', quantity: 100, unit: 'gram', pricePerUnit: 0, bakerPercentage: 20, isStarter: true },
      { id: 'zd1-4', name: 'Zout',        quantity: 10,  unit: 'gram', pricePerUnit: 0.80, bakerPercentage: 2 },
    ],
    instructions: [
      'Meng bloem en 90% van het water en laat 30 tot 60 minuten rusten (autolyse).',
      'Voeg de zuurdesemstarter toe en meng goed.',
      'Voeg het zout en het resterende water toe.',
      'Doe 3 tot 4 stretch & folds tijdens de bulkrijs.',
      'Laat het deeg rijzen tot ongeveer 30 tot 50% volumetoename.',
      'Vorm het deeg strak op.',
      'Laat 2 tot 3 uur narijzen op kamertemperatuur óf 10 tot 14 uur in de koelkast.',
      'Bak 20 minuten op 250 °C met stoom of in een gesloten gietijzeren pan.',
      'Bak daarna 20 tot 25 minuten op 220 °C zonder stoom of zonder deksel.',
    ],
    fermentation:
      'Bulkrijs: 4–6 u op kamertemperatuur (22–24 °C) tot 30–50% volumetoename. Narijs: kort op kamertemp. of liefst 10–14 u koud (4 °C) voor diepere smaak.',
    baking: '20 min op 250 °C (met stoom/deksel) + 20–25 min op 220 °C (zonder stoom).',
  },
  {
    id: 'zd-rustiek',
    name: 'Rustiek zuurdesembrood',
    category: 'Brood',
    subcategory: 'Zuurdesem',
    baseYield: 1,
    yieldUnit: 'brood',
    difficulty: 'Gemiddeld',
    prepTime: 1140,
    activeLaborMinutes: 10,
    suggestedPackagingCost: 0.05,
    photo: 'https://images.unsplash.com/photo-1620921592619-652411a0d01a?w=600&q=80',
    description:
      'Een smaakvoller zuurdesembrood met volkorenmeel voor meer karakter en een stevigere kruim.',
    baseFlourGrams: 500,
    ingredients: [
      { id: 'zd2-1', name: 'Tarwebloem',   quantity: 400, unit: 'gram', pricePerUnit: 1.20, bakerPercentage: 80 },
      { id: 'zd2-2', name: 'Volkorenmeel', quantity: 100, unit: 'gram', pricePerUnit: 1.40, bakerPercentage: 20 },
      { id: 'zd2-3', name: 'Water',        quantity: 360, unit: 'gram', pricePerUnit: 0,    bakerPercentage: 72 },
      { id: 'zd2-4', name: 'Zuurdesemstarter (100% hydr.)', quantity: 100, unit: 'gram', pricePerUnit: 0, bakerPercentage: 20, isStarter: true },
      { id: 'zd2-5', name: 'Zout',         quantity: 10,  unit: 'gram', pricePerUnit: 0.80, bakerPercentage: 2 },
    ],
    instructions: [
      'Meng bloem, volkorenmeel en 90% van het water en laat 45 tot 60 minuten rusten.',
      'Voeg de zuurdesemstarter toe en meng goed.',
      'Voeg het zout en resterend water toe.',
      'Doe 3 tot 4 stretch & folds tijdens de bulkrijs.',
      'Laat het deeg 4 tot 6 uur fermenteren, afhankelijk van temperatuur.',
      'Vorm het deeg op.',
      'Laat koud narijzen voor extra smaak: 10 tot 14 uur in de koelkast.',
      'Bak 20 minuten op 250 °C met stoom of deksel.',
      'Bak daarna 25 minuten op 220 °C zonder stoom of deksel.',
    ],
    fermentation:
      'Bulkrijs: 4–6 u op 22–24 °C. Volkoren versnelt fermentatie — controleer op 30–50% volumetoename. Narijs: 10–14 u koud voor robuuste smaak.',
    baking: '20 min op 250 °C (met stoom/deksel) + 25 min op 220 °C (zonder stoom).',
  },
  {
    id: 'zd-high-hydration',
    name: 'Vochtrijk zuurdesembrood',
    category: 'Brood',
    subcategory: 'Zuurdesem',
    baseYield: 1,
    yieldUnit: 'brood',
    difficulty: 'Moeilijk',
    prepTime: 1200,
    activeLaborMinutes: 12,
    suggestedPackagingCost: 0.05,
    photo: 'https://images.unsplash.com/photo-1590301157172-7ba48dd1c2b2?w=600&q=80',
    description:
      'Een luchtig artisan zuurdesembrood met hogere hydratatie en een open kruim.',
    baseFlourGrams: 500,
    ingredients: [
      { id: 'zd3-1', name: 'Sterke tarwebloem', quantity: 500, unit: 'gram', pricePerUnit: 1.40, bakerPercentage: 100 },
      { id: 'zd3-2', name: 'Water',             quantity: 385, unit: 'gram', pricePerUnit: 0,    bakerPercentage: 77 },
      { id: 'zd3-3', name: 'Zuurdesemstarter (100% hydr.)', quantity: 100, unit: 'gram', pricePerUnit: 0, bakerPercentage: 20, isStarter: true },
      { id: 'zd3-4', name: 'Zout',              quantity: 10,  unit: 'gram', pricePerUnit: 0.80, bakerPercentage: 2 },
    ],
    instructions: [
      'Meng bloem en 90% van het water en laat 60 minuten rusten (autolyse).',
      'Voeg de starter toe en meng rustig.',
      'Voeg het zout en het resterende water toe.',
      'Werk met coil folds of stretch & folds, 4 tot 5 keer tijdens de bulkrijs.',
      'Laat het deeg rijzen tot 30 tot 50% volumetoename.',
      'Vorm voorzichtig op om lucht in het deeg te behouden.',
      'Laat 10 tot 14 uur narijzen in de koelkast.',
      'Bak 20 minuten op 250 °C met stoom of deksel.',
      'Bak daarna 20 tot 25 minuten op 220 °C zonder stoom of deksel.',
    ],
    fermentation:
      'Bulkrijs: 5–7 u op 22–24 °C met coil folds elke 30–45 min. Hogere hydratatie = voorzichtiger handelen. Narijs altijd koud (10–14 u).',
    baking: '20 min op 250 °C (met stoom/deksel) + 20–25 min op 220 °C (zonder stoom).',
  },
  // ─── Zoet gebak ────────────────────────────────────────────
  {
    id: 'cinnamon-rolls',
    name: 'Cinnamon Rolls',
    category: 'Zoet gebak',
    baseYield: 12,
    yieldUnit: 'stuks',
    difficulty: 'Gemiddeld',
    prepTime: 120,
    activeLaborMinutes: 60,
    suggestedPackagingCost: 0.1,
    photo: '/recipes/cinnamon-roll.jpg',
    ingredients: [
      { id: 'cr-1', name: 'Bloem', quantity: 500, unit: 'gram', pricePerUnit: 1.20 },
      { id: 'cr-2', name: 'Volle melk', quantity: 250, unit: 'ml', pricePerUnit: 1.10 },
      { id: 'cr-3', name: 'Boter', quantity: 80, unit: 'gram', pricePerUnit: 8.00 },
      { id: 'cr-4', name: 'Suiker', quantity: 60, unit: 'gram', pricePerUnit: 1.00 },
      { id: 'cr-5', name: 'Ei', quantity: 2, unit: 'stuk', pricePerUnit: 0.35 },
      { id: 'cr-6', name: 'Gist (gedroogd)', quantity: 7, unit: 'gram', pricePerUnit: 15.00 },
      { id: 'cr-11', name: 'Zout', quantity: 5, unit: 'gram', pricePerUnit: 0.80 },
      { id: 'cr-7', name: 'Kaneel', quantity: 10, unit: 'gram', pricePerUnit: 30.00 },
      { id: 'cr-8', name: 'Bruine suiker', quantity: 80, unit: 'gram', pricePerUnit: 1.50 },
      { id: 'cr-9', name: 'Boter (vulling)', quantity: 60, unit: 'gram', pricePerUnit: 8.00 },
      { id: 'cr-10', name: 'Poedersuiker', quantity: 100, unit: 'gram', pricePerUnit: 1.80 },
    ],
    description: 'Klassieke kaneelrolletjes met een rijk gistdeeg, romige glazuur en de lekkerste warm-uit-de-oven smaak.',
    instructions: [
      'Verwarm de melk lauw (ca. 35 °C) en los er de gist en suiker in op. Laat 10 minuten staan tot het schuimt.',
      'Meng de bloem en het zout in een grote kom. Voeg het ei, de zachte boter (80g) en het gistmengsel toe.',
      'Kneed 8-10 minuten tot het deeg soepel en elastisch is.',
      'Laat het deeg afgedekt 1 uur rijzen op een warme plek tot dubbele grootte.',
      'Rol uit tot een rechthoek van ongeveer 30×40 cm.',
      'Smeer met zachte boter (60g vulling), bestrooi met bruine suiker en kaneel.',
      'Rol strak op vanaf de lange zijde en snijd in 12 gelijke plakken.',
      'Leg in een ingevette bakvorm en laat 30-45 minuten narijzen.',
      'Bak 20-25 minuten op 180 °C tot goudbruin.',
      'Maak het glazuur met poedersuiker en een scheutje melk. Bedek de warme rolletjes vlak voor het serveren.',
    ],
    fermentation: 'Eerste rijs: 1 uur op kamertemperatuur (22-24 °C). Narijs in vorm: 30-45 min tot opgezwollen.',
    baking: '20-25 min op 180 °C tot goudbruin met zachte kern.',
  },
  // ─── Brood ─────────────────────────────────────────────────
  {
    id: 'koffiebroodjes',
    name: 'Koffiebroodjes',
    category: 'Brood',
    baseYield: 10,
    yieldUnit: 'stuks',
    difficulty: 'Gemiddeld',
    prepTime: 90,
    activeLaborMinutes: 45,
    suggestedPackagingCost: 0.08,
    photo: '/recipes/koffiebroodjes.jpg',
    ingredients: [
      { id: 'kb-1', name: 'Bloem', quantity: 450, unit: 'gram', pricePerUnit: 1.20 },
      { id: 'kb-2', name: 'Volle melk', quantity: 200, unit: 'ml', pricePerUnit: 1.10 },
      { id: 'kb-3', name: 'Boter', quantity: 100, unit: 'gram', pricePerUnit: 8.00 },
      { id: 'kb-4', name: 'Suiker', quantity: 50, unit: 'gram', pricePerUnit: 1.00 },
      { id: 'kb-5', name: 'Ei', quantity: 2, unit: 'stuk', pricePerUnit: 0.35 },
      { id: 'kb-6', name: 'Gist (gedroogd)', quantity: 7, unit: 'gram', pricePerUnit: 15.00 },
      { id: 'kb-7', name: 'Zout', quantity: 5, unit: 'gram', pricePerUnit: 0.80 },
      { id: 'kb-8', name: 'Rozijnen', quantity: 100, unit: 'gram', pricePerUnit: 6.00 },
      { id: 'kb-9', name: 'Ei (voor bestrijken)', quantity: 1, unit: 'stuk', pricePerUnit: 0.35 },
    ],
    description: 'Zachte zoete broodjes met rozijnen — perfect bij koffie of als ontbijt.',
    instructions: [
      'Verwarm de melk lauw en meng met de gist en suiker. Laat 10 minuten activeren.',
      'Meng de bloem en het zout in een kom. Voeg het gistmengsel, ei en zachte boter toe.',
      'Kneed 8-10 minuten tot een soepel deeg.',
      'Was de rozijnen, dep droog en kneed door het deeg.',
      'Laat afgedekt 1 uur rijzen op een warme plek.',
      'Verdeel in 10 gelijke stukken en vorm strakke bolletjes.',
      'Druk plat tot ovaalvorm en leg op een bakplaat met bakpapier.',
      'Laat 30-40 minuten narijzen tot opgezwollen.',
      'Bestrijk met losgeklopt ei.',
      'Bak 18-20 minuten op 180 °C tot goudbruin.',
    ],
    fermentation: 'Bulk: 60 min op 22-24 °C. Narijs: 30-40 min.',
    baking: '18-20 min op 180 °C.',
  },
  // ─── Cake ──────────────────────────────────────────────────
  {
    id: 'cake',
    name: 'Cake',
    category: 'Cake',
    baseYield: 12,
    yieldUnit: 'plakjes',
    difficulty: 'Makkelijk',
    prepTime: 60,
    activeLaborMinutes: 15,
    suggestedPackagingCost: 0.2,
    photo: '/recipes/cake.jpg',
    ingredients: [
      { id: 'vc-1', name: 'Bloem', quantity: 250, unit: 'gram', pricePerUnit: 1.20 },
      { id: 'vc-2', name: 'Boter', quantity: 200, unit: 'gram', pricePerUnit: 8.00 },
      { id: 'vc-3', name: 'Suiker', quantity: 200, unit: 'gram', pricePerUnit: 1.00 },
      { id: 'vc-4', name: 'Ei', quantity: 4, unit: 'stuk', pricePerUnit: 0.35 },
      { id: 'vc-5', name: 'Vanille-extract', quantity: 5, unit: 'ml', pricePerUnit: 80.00 },
      { id: 'vc-6', name: 'Bakpoeder', quantity: 8, unit: 'gram', pricePerUnit: 10.00 },
      { id: 'vc-7', name: 'Melk', quantity: 60, unit: 'ml', pricePerUnit: 1.10 },
      { id: 'vc-8', name: 'Zout', quantity: 3, unit: 'gram', pricePerUnit: 0.80 },
    ],
    description: 'Klassieke vanille cake — luchtig, boterig en eenvoudig.',
    instructions: [
      'Verwarm de oven voor op 170 °C en bekleed een cakevorm met bakpapier.',
      'Klop de zachte boter met de suiker romig en bleek (ca. 5 minuten).',
      'Voeg de eieren één voor één toe en blijf goed kloppen tussen elke toevoeging.',
      'Roer de vanille-extract erdoor.',
      'Zeef bloem, bakpoeder en zout boven de kom en spatel beetje bij beetje door het beslag.',
      'Voeg de melk toe en spatel tot een glad beslag (niet overmixen).',
      'Stort het beslag in de cakevorm en strijk glad.',
      'Bak 50-60 minuten tot een prikker er schoon uitkomt.',
      'Laat 10 minuten afkoelen in de vorm, daarna op een rooster verder afkoelen.',
    ],
    baking: '50-60 min op 170 °C, prikker-test: schoon = klaar.',
  },
  // ─── Koekjes ───────────────────────────────────────────────
  {
    id: 'gevulde-koek',
    name: 'Gevulde koek',
    category: 'Koekjes',
    baseYield: 12,
    yieldUnit: 'stuks',
    difficulty: 'Gemiddeld',
    prepTime: 75,
    activeLaborMinutes: 45,
    suggestedPackagingCost: 0.08,
    photo: '/recipes/gevulde-koek.jpeg',
    description:
      'Klassieke Hollandse gevulde koeken met amandelspijs en een hele amandel als decoratie.',
    ingredients: [
      { id: 'gk-1', name: 'Bloem', quantity: 250, unit: 'gram', pricePerUnit: 1.20 },
      { id: 'gk-2', name: 'Roomboter (koud)', quantity: 175, unit: 'gram', pricePerUnit: 8.50 },
      { id: 'gk-3', name: 'Suiker', quantity: 125, unit: 'gram', pricePerUnit: 1.00 },
      { id: 'gk-4', name: 'Ei (in deeg)', quantity: 1, unit: 'stuk', pricePerUnit: 0.35 },
      { id: 'gk-5', name: 'Snufje zout', quantity: 2, unit: 'gram', pricePerUnit: 0.80 },
      { id: 'gk-6', name: 'Citroenrasp', quantity: 1, unit: 'stuk', pricePerUnit: 0.40 },
      { id: 'gk-7', name: 'Amandelspijs', quantity: 250, unit: 'gram', pricePerUnit: 12.00 },
      { id: 'gk-8', name: 'Ei (voor bestrijken)', quantity: 1, unit: 'stuk', pricePerUnit: 0.35 },
      { id: 'gk-9', name: 'Hele amandelen', quantity: 12, unit: 'stuk', pricePerUnit: 0.10 },
    ],
    instructions: [
      'Meng bloem, suiker, snufje zout en citroenrasp in een kom.',
      'Voeg de koude boter in blokjes en het ei toe. Kneed snel tot een samenhangend deeg.',
      'Verpak in folie en laat minstens 30 minuten rusten in de koelkast.',
      'Verwarm de oven voor op 175 °C.',
      'Verdeel het deeg in 24 gelijke stukken (12 onderkanten + 12 deksels).',
      'Rol elk stukje uit tot een rondje van ongeveer 8 cm.',
      'Verdeel een bolletje amandelspijs (ca. 20 g) op elke onderkant.',
      'Plaats een bovenkant erop en druk de randen voorzichtig dicht.',
      'Bestrijk met losgeklopt ei en druk een hele amandel in het midden.',
      'Bak 20-25 minuten op 175 °C tot goudbruin.',
    ],
    baking: '20-25 min op 175 °C tot goudbruin.',
  },
  // ─── Taart ─────────────────────────────────────────────────
  {
    id: 'appeltaart',
    name: 'Appeltaart',
    category: 'Cake',
    baseYield: 8,
    yieldUnit: 'plakjes',
    difficulty: 'Gemiddeld',
    prepTime: 90,
    activeLaborMinutes: 45,
    suggestedPackagingCost: 0.30,
    photo: '/recipes/appeltaart.jpg',
    description:
      'Klassieke Hollandse appeltaart met kaneel, rozijnen en een knapperig korstdeeg.',
    ingredients: [
      { id: 'at-1', name: 'Bloem', quantity: 300, unit: 'gram', pricePerUnit: 1.20 },
      { id: 'at-2', name: 'Roomboter (koud)', quantity: 200, unit: 'gram', pricePerUnit: 8.50 },
      { id: 'at-3', name: 'Bruine basterdsuiker (deeg)', quantity: 125, unit: 'gram', pricePerUnit: 1.60 },
      { id: 'at-4', name: 'Ei (in deeg)', quantity: 1, unit: 'stuk', pricePerUnit: 0.35 },
      { id: 'at-5', name: 'Citroenrasp', quantity: 1, unit: 'stuk', pricePerUnit: 0.40 },
      { id: 'at-6', name: 'Snufje zout', quantity: 2, unit: 'gram', pricePerUnit: 0.80 },
      { id: 'at-7', name: 'Goudreinetten of Elstar', quantity: 1000, unit: 'gram', pricePerUnit: 2.50 },
      { id: 'at-12', name: 'Bruine basterdsuiker (vulling)', quantity: 50, unit: 'gram', pricePerUnit: 1.60 },
      { id: 'at-8', name: 'Kaneel (deeg)', quantity: 4, unit: 'gram', pricePerUnit: 30.00 },
      { id: 'at-13', name: 'Kaneel (vulling)', quantity: 4, unit: 'gram', pricePerUnit: 30.00 },
      { id: 'at-9', name: 'Rozijnen', quantity: 75, unit: 'gram', pricePerUnit: 6.00 },
      { id: 'at-10', name: 'Paneermeel', quantity: 30, unit: 'gram', pricePerUnit: 2.50 },
      { id: 'at-11', name: 'Ei (voor bestrijken)', quantity: 1, unit: 'stuk', pricePerUnit: 0.35 },
    ],
    instructions: [
      'Meng de bloem, basterdsuiker (deeg, 125g), kaneel (deeg, 4g), citroenrasp en zout.',
      'Voeg de koude boter in blokjes en het ei toe. Kneed kort tot een samenhangend deeg.',
      'Verpak in folie en laat 30 minuten rusten in de koelkast.',
      'Schil de appels, snijd in partjes en mix met de rozijnen, basterdsuiker (vulling, 50g) en kaneel (vulling, 4g).',
      'Vet een springvorm (24 cm) in en bekleed met 2/3 van het deeg (bodem + zijkant ca. 5 cm).',
      'Strooi het paneermeel op de bodem — dit vangt het appelsap op.',
      'Vul stevig met het appelmengsel.',
      'Rol de rest van het deeg uit en snijd strookjes voor het ruitenpatroon.',
      'Bestrijk de strookjes met losgeklopt ei.',
      'Bak 60-70 minuten op 180 °C tot goudbruin.',
      'Laat volledig afkoelen vóór het aansnijden — dit voorkomt dat de vulling uitloopt.',
    ],
    baking: '60-70 min op 180 °C. Volledig laten afkoelen.',
  },
  {
    id: 'vruchtentaart',
    name: 'Vruchtentaart',
    category: 'Cake',
    baseYield: 8,
    yieldUnit: 'plakjes',
    difficulty: 'Gemiddeld',
    prepTime: 75,
    activeLaborMinutes: 50,
    suggestedPackagingCost: 0.30,
    photo: '/recipes/vruchtentaart.jpg',
    description:
      'Frisse vruchtentaart met biscuitbodem, banketbakkersroom en seizoensfruit.',
    ingredients: [
      { id: 'vt-1', name: 'Bloem (biscuit)', quantity: 100, unit: 'gram', pricePerUnit: 1.20 },
      { id: 'vt-2', name: 'Suiker (biscuit)', quantity: 100, unit: 'gram', pricePerUnit: 1.00 },
      { id: 'vt-3', name: 'Ei (biscuit)', quantity: 4, unit: 'stuk', pricePerUnit: 0.35 },
      { id: 'vt-4', name: 'Vanille-extract', quantity: 5, unit: 'ml', pricePerUnit: 80.00 },
      { id: 'vt-5', name: 'Volle melk (room)', quantity: 500, unit: 'ml', pricePerUnit: 1.10 },
      { id: 'vt-6', name: 'Eidooier (room)', quantity: 4, unit: 'stuk', pricePerUnit: 0.35 },
      { id: 'vt-7', name: 'Suiker (room)', quantity: 100, unit: 'gram', pricePerUnit: 1.00 },
      { id: 'vt-8', name: 'Maizena', quantity: 40, unit: 'gram', pricePerUnit: 3.00 },
      { id: 'vt-9', name: 'Vers fruit (mix)', quantity: 400, unit: 'gram', pricePerUnit: 8.00 },
      { id: 'vt-10', name: 'Abrikozenjam (glazuur)', quantity: 80, unit: 'gram', pricePerUnit: 4.50 },
    ],
    instructions: [
      'BISCUIT: klop de eieren met de suiker 8-10 minuten luchtig (lint-stadium).',
      'Roer de vanille-extract erdoor en zeef de bloem boven de kom.',
      'Spatel voorzichtig door (verlies geen lucht) en stort in een ingevette springvorm (24 cm).',
      'Bak 20-25 minuten op 180 °C tot lichtgoud en veerkrachtig.',
      'Laat volledig afkoelen.',
      'BANKETBAKKERSROOM: verwarm de melk in een steelpan tot tegen het kookpunt.',
      'Klop dooiers met suiker en maizena tot bleek en luchtig.',
      'Giet de warme melk al kloppend bij het dooier-mengsel.',
      'Terug in de pan en blijf roeren op middelhoog vuur tot de room bindt (3-5 min).',
      'Stort in een schaal, dek af met folie op de room (geen velvorming) en koel.',
      'AFBOUW: snijd de biscuit in 2 lagen. Vul met de afgekoelde room en plaats de bovenkant terug.',
      'Beleg royaal met vers fruit in een mooi patroon.',
      'Verwarm de abrikozenjam met een scheutje water en kwast over het fruit voor glans.',
      'Koel minimaal 1 uur voor het serveren.',
    ],
    baking: 'Biscuit: 20-25 min op 180 °C.',
  },
  // ─── Brood (extra) ─────────────────────────────────────────
  {
    id: 'krentenbollen',
    name: 'Krentenbollen',
    category: 'Brood',
    baseYield: 12,
    yieldUnit: 'stuks',
    difficulty: 'Makkelijk',
    prepTime: 90,
    activeLaborMinutes: 35,
    suggestedPackagingCost: 0.05,
    photo: '/recipes/krentenbollen.jpg',
    description:
      'Zachte zoete bollen rijkelijk gevuld met krenten en rozijnen.',
    ingredients: [
      { id: 'kr-1', name: 'Bloem', quantity: 500, unit: 'gram', pricePerUnit: 1.20 },
      { id: 'kr-2', name: 'Volle melk', quantity: 250, unit: 'ml', pricePerUnit: 1.10 },
      { id: 'kr-3', name: 'Boter', quantity: 60, unit: 'gram', pricePerUnit: 8.00 },
      { id: 'kr-4', name: 'Suiker', quantity: 60, unit: 'gram', pricePerUnit: 1.00 },
      { id: 'kr-5', name: 'Ei (in deeg)', quantity: 1, unit: 'stuk', pricePerUnit: 0.35 },
      { id: 'kr-6', name: 'Gist (gedroogd)', quantity: 7, unit: 'gram', pricePerUnit: 15.00 },
      { id: 'kr-7', name: 'Zout', quantity: 8, unit: 'gram', pricePerUnit: 0.80 },
      { id: 'kr-8', name: 'Krenten', quantity: 150, unit: 'gram', pricePerUnit: 7.00 },
      { id: 'kr-9', name: 'Rozijnen', quantity: 100, unit: 'gram', pricePerUnit: 6.00 },
      { id: 'kr-10', name: 'Ei (voor bestrijken)', quantity: 1, unit: 'stuk', pricePerUnit: 0.35 },
    ],
    instructions: [
      'Verwarm de melk lauw en meng met de gist en suiker. Laat 10 min activeren.',
      'Meng bloem en zout in een kom. Voeg gistmengsel, ei en zachte boter toe.',
      'Kneed 8-10 minuten tot een soepel deeg.',
      'Was de krenten en rozijnen, dep droog en kneed door het deeg.',
      'Laat afgedekt 1 uur rijzen op een warme plek tot dubbele grootte.',
      'Verdeel in 12 gelijke stukken en vorm strakke bolletjes.',
      'Leg op een bakplaat met bakpapier en laat 30-40 minuten narijzen.',
      'Bestrijk met losgeklopt ei.',
      'Bak 18-20 minuten op 200 °C tot goudbruin.',
    ],
    fermentation: 'Bulk: 60 min op 22-24 °C. Narijs: 30-40 min.',
    baking: '18-20 min op 200 °C.',
  },
  {
    id: 'croissants',
    name: 'Croissants',
    category: 'Brood',
    baseYield: 12,
    yieldUnit: 'stuks',
    difficulty: 'Moeilijk',
    prepTime: 720,
    activeLaborMinutes: 90,
    suggestedPackagingCost: 0.10,
    photo: '/recipes/croissants.jpg',
    description:
      'Boterachtige laagjes croissants — vraagt geduld en koude boter, maar het resultaat is bakkerijwaardig.',
    ingredients: [
      { id: 'cs-1', name: 'Bloem', quantity: 500, unit: 'gram', pricePerUnit: 1.20 },
      { id: 'cs-2', name: 'Volle melk', quantity: 220, unit: 'ml', pricePerUnit: 1.10 },
      { id: 'cs-3', name: 'Boter (in deeg)', quantity: 50, unit: 'gram', pricePerUnit: 8.50 },
      { id: 'cs-4', name: 'Suiker', quantity: 55, unit: 'gram', pricePerUnit: 1.00 },
      { id: 'cs-5', name: 'Gist (gedroogd)', quantity: 7, unit: 'gram', pricePerUnit: 15.00 },
      { id: 'cs-6', name: 'Zout', quantity: 10, unit: 'gram', pricePerUnit: 0.80 },
      { id: 'cs-7', name: 'Roomboter (toerenbeslag)', quantity: 250, unit: 'gram', pricePerUnit: 8.50 },
      { id: 'cs-8', name: 'Ei (voor bestrijken)', quantity: 1, unit: 'stuk', pricePerUnit: 0.35 },
    ],
    instructions: [
      'Meng bloem, suiker, zout, gist en de zachte boter (50 g) in een kom.',
      'Voeg melk toe en kneed tot een soepel deeg. Laat 1 uur rijzen op kamertemperatuur.',
      'Plat het deeg af tot rechthoek, verpak in folie en leg 1 uur in de koelkast.',
      'Vorm de toerenboter (250 g) in een vierkant van 20×20 cm tussen 2 vellen folie. Houd koud.',
      'Rol het deeg uit tot een rechthoek van 40×20 cm. Leg de boter in het midden.',
      'Vouw de zijkanten over de boter (eerste toer = enveloppe).',
      'Rol uit tot rechthoek en geef een drievoudige toer. Koel 30 minuten.',
      'Herhaal de drievoudige toer nog 2 keer met telkens 30 minuten koelen ertussen (totaal 3 toeren).',
      'Rol uit tot een grote rechthoek en snijd 12 gelijke driehoeken (basis ca. 9 cm, hoogte ca. 24 cm).',
      'Rol elk driehoek op vanaf de brede kant naar de punt en plaats op een bakplaat.',
      'Laat 2 uur narijzen op kamertemperatuur.',
      'Bestrijk met losgeklopt ei.',
      'Bak 15-18 minuten op 200 °C tot goudbruin en knapperig.',
    ],
    fermentation: 'Eerste rijs: 1 u op kamertemp. Tussendoor 30 min koeling per toer. Narijs: 2 u op kamertemp.',
    baking: '15-18 min op 200 °C.',
  },
  {
    id: 'luxe-broodjes',
    name: 'Luxe broodjes',
    category: 'Brood',
    baseYield: 12,
    yieldUnit: 'stuks',
    difficulty: 'Makkelijk',
    prepTime: 90,
    activeLaborMinutes: 35,
    suggestedPackagingCost: 0.06,
    photo: '/recipes/luxe-broodjes.jpg',
    description:
      'Zachte, rijke broodjes met boter en ei — perfect voor brunch of zondagochtend.',
    ingredients: [
      { id: 'lb-1', name: 'Bloem', quantity: 500, unit: 'gram', pricePerUnit: 1.20 },
      { id: 'lb-2', name: 'Volle melk', quantity: 250, unit: 'ml', pricePerUnit: 1.10 },
      { id: 'lb-3', name: 'Boter', quantity: 80, unit: 'gram', pricePerUnit: 8.00 },
      { id: 'lb-4', name: 'Suiker', quantity: 50, unit: 'gram', pricePerUnit: 1.00 },
      { id: 'lb-5', name: 'Ei (in deeg)', quantity: 2, unit: 'stuk', pricePerUnit: 0.35 },
      { id: 'lb-6', name: 'Gist (gedroogd)', quantity: 7, unit: 'gram', pricePerUnit: 15.00 },
      { id: 'lb-7', name: 'Zout', quantity: 8, unit: 'gram', pricePerUnit: 0.80 },
      { id: 'lb-8', name: 'Ei (voor bestrijken)', quantity: 1, unit: 'stuk', pricePerUnit: 0.35 },
    ],
    instructions: [
      'Verwarm de melk lauw en meng met de gist en suiker. Laat 10 min activeren.',
      'Meng bloem en zout in een grote kom.',
      'Voeg het gistmengsel, eieren en zachte boter toe.',
      'Kneed 10 minuten tot een soepel, elastisch deeg.',
      'Laat 1 uur rijzen op een warme plek tot dubbele grootte.',
      'Verdeel in 12 gelijke stukken en vorm strakke bolletjes.',
      'Leg op een bakplaat met bakpapier (op afstand van elkaar).',
      'Laat 30-45 minuten narijzen.',
      'Bestrijk met losgeklopt ei.',
      'Bak 15-18 minuten op 200 °C tot goudbruin.',
    ],
    fermentation: 'Bulk: 60 min op 22-24 °C. Narijs: 30-45 min.',
    baking: '15-18 min op 200 °C.',
  },

  // ─── Brood (extra) ───────────────────────────────────────
  {
    id: 'tijgerbrood',
    name: 'Tijgerbrood',
    category: 'Brood',
    baseYield: 1,
    yieldUnit: 'brood',
    difficulty: 'Gemiddeld',
    prepTime: 180,
    activeLaborMinutes: 25,
    suggestedPackagingCost: 0.05,
    photo: 'https://images.unsplash.com/photo-1568471173242-461f0a730452?w=600&q=80',
    description:
      'Zacht wit brood met de iconische krokante tijgerprint van rijstebloem-pasta op de korst.',
    ingredients: [
      { id: 'tb-1', name: 'Tarwebloem', quantity: 500, unit: 'gram', pricePerUnit: 1.20 },
      { id: 'tb-2', name: 'Water', quantity: 300, unit: 'ml', pricePerUnit: 0 },
      { id: 'tb-3', name: 'Gedroogde gist', quantity: 7, unit: 'gram', pricePerUnit: 15.00 },
      { id: 'tb-4', name: 'Zout', quantity: 9, unit: 'gram', pricePerUnit: 0.80 },
      { id: 'tb-5', name: 'Zonnebloemolie', quantity: 20, unit: 'ml', pricePerUnit: 2.50 },
      { id: 'tb-6', name: 'Maizena (maïszetmeel)', quantity: 50, unit: 'gram', pricePerUnit: 2.20 },
      { id: 'tb-7', name: 'Sesamolie', quantity: 5, unit: 'ml', pricePerUnit: 8.00 },
    ],
    instructions: [
      'Meng bloem, gist en zout in een kom.',
      'Voeg lauw water en olie toe en kneed 10 minuten tot soepel deeg.',
      'Laat 1 uur rijzen tot dubbele grootte.',
      'Vorm tot brood en leg in een ingevet brood-blik of vrije vorm.',
      'Meng maizena met warm water + sesamolie tot een pasta (consistentie van yoghurt).',
      'Strijk de pasta dik over het deeg na 20 min narijzen.',
      'Laat verder narijzen tot 40 min.',
      'Bak 25-30 min op 220 °C — de pasta breekt open tot een tijgerpatroon.',
    ],
    fermentation: 'Bulk: 1 u op 24 °C. Narijs: 40 min met pasta-laag.',
    baking: '25-30 min op 220 °C.',
  },
  {
    id: 'focaccia',
    name: 'Focaccia',
    category: 'Brood',
    baseYield: 1,
    yieldUnit: 'plaat (35x25 cm)',
    difficulty: 'Makkelijk',
    prepTime: 240,
    activeLaborMinutes: 15,
    suggestedPackagingCost: 0.10,
    photo: 'https://images.unsplash.com/photo-1612966292330-cbe1f4b9f8ab?w=600&q=80',
    description:
      'Italiaans vlak brood met luchtige binnenkant, krokante korst en flink wat olijfolie. Perfect met rozemarijn en zeezout.',
    ingredients: [
      { id: 'fc-1', name: 'Tarwebloem', quantity: 500, unit: 'gram', pricePerUnit: 1.20 },
      { id: 'fc-2', name: 'Water', quantity: 400, unit: 'ml', pricePerUnit: 0 },
      { id: 'fc-3', name: 'Gedroogde gist', quantity: 5, unit: 'gram', pricePerUnit: 15.00 },
      { id: 'fc-4', name: 'Zout', quantity: 10, unit: 'gram', pricePerUnit: 0.80 },
      { id: 'fc-5', name: 'Olijfolie', quantity: 60, unit: 'ml', pricePerUnit: 9.00 },
    ],
    instructions: [
      'Meng bloem, gist en zout. Voeg water + 30ml olijfolie toe.',
      'Meng kort tot een ruw, plakkerig deeg (geen lang kneden nodig).',
      'Dek af en laat 30 min rusten. Doe een stretch & fold.',
      'Herhaal nog 2x met 30 min tussenpoos.',
      'Laat 1 uur verder rijzen tot luchtig.',
      'Olie een bakvorm rijk in en plaats het deeg erin. Druk vingertopgaatjes diep in het deeg.',
      'Besprenkel met resterende olijfolie, grof zeezout en (optioneel) rozemarijn.',
      'Bak 20-25 min op 230 °C tot goudbruin.',
    ],
    fermentation: 'Bulk: 3 u met 3x stretch & fold. Narijs: 30 min in vorm.',
    baking: '20-25 min op 230 °C.',
  },

  // ─── Zoet gebak (extra) ──────────────────────────────────
  {
    id: 'appelflap',
    name: 'Appelflap',
    category: 'Zoet gebak',
    baseYield: 8,
    yieldUnit: 'stuks',
    difficulty: 'Makkelijk',
    prepTime: 60,
    activeLaborMinutes: 30,
    suggestedPackagingCost: 0.15,
    photo: 'https://images.unsplash.com/photo-1572383672419-ab35444a6934?w=600&q=80',
    description:
      'Klassieke Nederlandse appelflap: bladerdeeg gevuld met zachte kaneel-appel en bedekt met grove suiker.',
    ingredients: [
      { id: 'af-1', name: 'Bladerdeeg (8 plakjes)', quantity: 400, unit: 'gram', pricePerUnit: 4.50 },
      { id: 'af-2', name: 'Appel (Goudreinet)', quantity: 600, unit: 'gram', pricePerUnit: 2.50 },
      { id: 'af-3', name: 'Kristalsuiker', quantity: 60, unit: 'gram', pricePerUnit: 1.00 },
      { id: 'af-4', name: 'Kaneel', quantity: 3, unit: 'gram', pricePerUnit: 30.00 },
      { id: 'af-5', name: 'Rozijnen', quantity: 40, unit: 'gram', pricePerUnit: 4.00 },
      { id: 'af-6', name: 'Heel ei', quantity: 1, unit: 'stuk', pricePerUnit: 0.35 },
      { id: 'af-7', name: 'Parelsuiker', quantity: 30, unit: 'gram', pricePerUnit: 3.00 },
    ],
    instructions: [
      'Laat bladerdeeg ontdooien op aanrecht (10 min).',
      'Schil appels en snijd in kleine blokjes (~5 mm).',
      'Meng appel met suiker, kaneel en rozijnen. Laat 10 min staan.',
      'Leg een hoopje vulling op elk plakje bladerdeeg.',
      'Bestrijk de randen met losgeklopt ei.',
      'Vouw tot driehoek en druk randen stevig dicht met vork.',
      'Bestrijk de bovenkant met ei en bestrooi met parelsuiker.',
      'Bak 20-25 min op 200 °C tot goudbruin en bladerig.',
    ],
    baking: '20-25 min op 200 °C, midden in de oven.',
  },
  {
    id: 'tompoes',
    name: 'Tompoes',
    category: 'Zoet gebak',
    baseYield: 8,
    yieldUnit: 'stuks',
    difficulty: 'Gemiddeld',
    prepTime: 120,
    activeLaborMinutes: 45,
    suggestedPackagingCost: 0.25,
    photo: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=600&q=80',
    description:
      'Hollandse klassieker met twee lagen knapperig bladerdeeg, gele banketbakkersroom en roze glazuur.',
    ingredients: [
      { id: 'tp-1', name: 'Bladerdeeg (16 plakjes)', quantity: 800, unit: 'gram', pricePerUnit: 4.50 },
      { id: 'tp-2', name: 'Volle melk', quantity: 500, unit: 'ml', pricePerUnit: 1.10 },
      { id: 'tp-3', name: 'Heel ei', quantity: 4, unit: 'stuk', pricePerUnit: 0.35 },
      { id: 'tp-4', name: 'Kristalsuiker', quantity: 120, unit: 'gram', pricePerUnit: 1.00 },
      { id: 'tp-5', name: 'Maizena (maïszetmeel)', quantity: 40, unit: 'gram', pricePerUnit: 2.20 },
      { id: 'tp-6', name: 'Vanille-extract', quantity: 5, unit: 'ml', pricePerUnit: 25.00 },
      { id: 'tp-7', name: 'Poedersuiker', quantity: 200, unit: 'gram', pricePerUnit: 1.80 },
      { id: 'tp-8', name: 'Roze voedingskleurstof', quantity: 1, unit: 'gram', pricePerUnit: 50.00 },
    ],
    instructions: [
      'Bak het bladerdeeg in 2 vellen tussen 2 bakplaten op 200 °C, ~20 min — moet plat en knapperig blijven.',
      'Voor banketbakkersroom: verwarm melk met halve vanille.',
      'Klop eierdooiers met suiker en maizena tot lichtgeel.',
      'Voeg warme melk al kloppend toe en breng al roerend aan de kook.',
      'Kook 2 min tot dikke crème. Laat afkoelen onder folie (contact).',
      'Smeer de banketbakkersroom dik op één laag bladerdeeg, leg tweede laag erop.',
      'Snijd voorzichtig in 8 stukken.',
      'Maak glazuur van poedersuiker + 2-3 el water + kleurstof. Smeer op bovenkant.',
    ],
    baking: 'Bladerdeeg: 20 min op 200 °C tussen 2 bakplaten.',
  },
  {
    id: 'bossche-bol',
    name: 'Bossche bol',
    category: 'Zoet gebak',
    baseYield: 6,
    yieldUnit: 'stuks',
    difficulty: 'Moeilijk',
    prepTime: 150,
    activeLaborMinutes: 60,
    suggestedPackagingCost: 0.30,
    photo: 'https://images.unsplash.com/photo-1606312619070-d48b4c652a52?w=600&q=80',
    description:
      'Brabantse trots: een grote soes gevuld met slagroom en bedekt met een dikke laag pure chocolade.',
    ingredients: [
      { id: 'bb-1', name: 'Water', quantity: 250, unit: 'ml', pricePerUnit: 0 },
      { id: 'bb-2', name: 'Roomboter (ongezouten)', quantity: 100, unit: 'gram', pricePerUnit: 8.00 },
      { id: 'bb-3', name: 'Tarwebloem', quantity: 150, unit: 'gram', pricePerUnit: 1.20 },
      { id: 'bb-4', name: 'Heel ei', quantity: 4, unit: 'stuk', pricePerUnit: 0.35 },
      { id: 'bb-5', name: 'Zout', quantity: 2, unit: 'gram', pricePerUnit: 0.80 },
      { id: 'bb-6', name: 'Slagroom', quantity: 500, unit: 'ml', pricePerUnit: 3.50 },
      { id: 'bb-7', name: 'Poedersuiker (voor room)', quantity: 30, unit: 'gram', pricePerUnit: 1.80 },
      { id: 'bb-8', name: 'Pure chocolade (70%)', quantity: 250, unit: 'gram', pricePerUnit: 5.50 },
    ],
    instructions: [
      'Breng water, boter en zout aan de kook in een pan.',
      'Voeg alle bloem in één keer toe en roer fel tot het deeg loslaat van de pan (~2 min).',
      'Laat 5 min afkoelen, dan beetje bij beetje eieren erdoor mengen tot glanzend, soepel deeg.',
      'Spuit/lepel 6 grote bollen (ø 8 cm) op bakpapier.',
      'Bak 15 min op 220 °C, dan 25 min op 180 °C tot stevig en goudbruin.',
      'Laat volledig afkoelen. Snijd horizontaal door midden.',
      'Klop slagroom met poedersuiker stijf en vul ruim.',
      'Smelt chocolade au bain-marie en doop de bovenkant. Laat opstijven.',
    ],
    baking: '15 min op 220 °C + 25 min op 180 °C.',
  },
  {
    id: 'donut',
    name: 'Suikerdonut',
    category: 'Zoet gebak',
    baseYield: 12,
    yieldUnit: 'stuks',
    difficulty: 'Gemiddeld',
    prepTime: 150,
    activeLaborMinutes: 40,
    suggestedPackagingCost: 0.12,
    photo: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?w=600&q=80',
    description:
      'Luchtige gefrituurde donuts met een kaneel-suiker laagje. Klassiek én onweerstaanbaar.',
    ingredients: [
      { id: 'dn-1', name: 'Tarwebloem', quantity: 500, unit: 'gram', pricePerUnit: 1.20 },
      { id: 'dn-2', name: 'Volle melk', quantity: 220, unit: 'ml', pricePerUnit: 1.10 },
      { id: 'dn-3', name: 'Kristalsuiker', quantity: 60, unit: 'gram', pricePerUnit: 1.00 },
      { id: 'dn-4', name: 'Roomboter (ongezouten)', quantity: 50, unit: 'gram', pricePerUnit: 8.00 },
      { id: 'dn-5', name: 'Heel ei', quantity: 2, unit: 'stuk', pricePerUnit: 0.35 },
      { id: 'dn-6', name: 'Gedroogde gist', quantity: 7, unit: 'gram', pricePerUnit: 15.00 },
      { id: 'dn-7', name: 'Zout', quantity: 5, unit: 'gram', pricePerUnit: 0.80 },
      { id: 'dn-8', name: 'Zonnebloemolie', quantity: 1000, unit: 'ml', pricePerUnit: 2.50 },
      { id: 'dn-9', name: 'Kaneel', quantity: 5, unit: 'gram', pricePerUnit: 30.00 },
      { id: 'dn-10', name: 'Kristalsuiker (topping)', quantity: 100, unit: 'gram', pricePerUnit: 1.00 },
    ],
    instructions: [
      'Verwarm melk lauw, los gist + 1 el suiker hierin op. 10 min laten staan.',
      'Meng bloem, suiker, zout, eieren en zachte boter. Voeg het gistmengsel toe.',
      'Kneed 10 min tot soepel deeg. Laat 1 u rijzen tot dubbele grootte.',
      'Rol uit tot 1,5 cm dik. Steek rondjes (ø 8 cm) met gat (ø 3 cm) erin.',
      'Leg op met meel bestoven bakpapier en laat 45 min narijzen.',
      'Verhit olie tot 175 °C. Bak donuts 1-1,5 min per kant goudbruin.',
      'Laat uitlekken op keukenpapier.',
      'Wentel direct door mengsel van kristalsuiker + kaneel.',
    ],
    fermentation: '60 min bulk + 45 min narijs.',
    baking: 'Frituren: 1-1,5 min per kant op 175 °C.',
  },

  // ─── Cake (extra) ────────────────────────────────────────
  {
    id: 'brownie',
    name: 'Fudgy brownie',
    category: 'Cake',
    baseYield: 16,
    yieldUnit: 'stuks',
    difficulty: 'Makkelijk',
    prepTime: 75,
    activeLaborMinutes: 20,
    suggestedPackagingCost: 0.08,
    photo: 'https://images.unsplash.com/photo-1610450949065-1f2841536c88?w=600&q=80',
    description:
      'Donkere, plakkerig-zachte brownie met een dunne krokante laag bovenop. Maximale chocolade-intensiteit.',
    ingredients: [
      { id: 'br-1', name: 'Pure chocolade (70%)', quantity: 200, unit: 'gram', pricePerUnit: 5.50 },
      { id: 'br-2', name: 'Roomboter (ongezouten)', quantity: 200, unit: 'gram', pricePerUnit: 8.00 },
      { id: 'br-3', name: 'Kristalsuiker', quantity: 250, unit: 'gram', pricePerUnit: 1.00 },
      { id: 'br-4', name: 'Heel ei', quantity: 4, unit: 'stuk', pricePerUnit: 0.35 },
      { id: 'br-5', name: 'Tarwebloem', quantity: 100, unit: 'gram', pricePerUnit: 1.20 },
      { id: 'br-6', name: 'Cacaopoeder', quantity: 30, unit: 'gram', pricePerUnit: 12.00 },
      { id: 'br-7', name: 'Zout', quantity: 2, unit: 'gram', pricePerUnit: 0.80 },
      { id: 'br-8', name: 'Walnoten', quantity: 80, unit: 'gram', pricePerUnit: 12.00 },
    ],
    instructions: [
      'Verwarm oven op 175 °C en bekleed brownievorm (20x20 cm) met bakpapier.',
      'Smelt chocolade en boter au bain-marie. Laat 5 min afkoelen.',
      'Klop suiker met eieren tot luchtig en bleek (~3 min).',
      'Spatel het chocolade-mengsel door het eier-suikermengsel.',
      'Zeef bloem + cacao + zout erbij en spatel voorzichtig door.',
      'Vouw walnoten erdoor.',
      'Stort in vorm en bak 25-30 min — kern mag nog zacht zijn.',
      'Laat volledig afkoelen voor je snijdt.',
    ],
    baking: '25-30 min op 175 °C — kern licht zacht laten voor fudgy resultaat.',
  },
  {
    id: 'citroencake',
    name: 'Citroencake',
    category: 'Cake',
    baseYield: 1,
    yieldUnit: 'cake (1 kg)',
    difficulty: 'Makkelijk',
    prepTime: 90,
    activeLaborMinutes: 20,
    suggestedPackagingCost: 0.20,
    photo: 'https://images.unsplash.com/photo-1519869325930-281384150729?w=600&q=80',
    description:
      'Frisse, vochtige cake met geraspte citroen in het beslag en een citroen-suikerglazuur erover.',
    ingredients: [
      { id: 'cc-1', name: 'Tarwebloem', quantity: 250, unit: 'gram', pricePerUnit: 1.20 },
      { id: 'cc-2', name: 'Kristalsuiker', quantity: 220, unit: 'gram', pricePerUnit: 1.00 },
      { id: 'cc-3', name: 'Roomboter (ongezouten)', quantity: 220, unit: 'gram', pricePerUnit: 8.00 },
      { id: 'cc-4', name: 'Heel ei', quantity: 4, unit: 'stuk', pricePerUnit: 0.35 },
      { id: 'cc-5', name: 'Bakpoeder', quantity: 8, unit: 'gram', pricePerUnit: 6.00 },
      { id: 'cc-6', name: 'Citroensap', quantity: 60, unit: 'ml', pricePerUnit: 4.00 },
      { id: 'cc-7', name: 'Citroenrasp', quantity: 10, unit: 'gram', pricePerUnit: 0 },
      { id: 'cc-8', name: 'Zout', quantity: 2, unit: 'gram', pricePerUnit: 0.80 },
      { id: 'cc-9', name: 'Poedersuiker', quantity: 100, unit: 'gram', pricePerUnit: 1.80 },
    ],
    instructions: [
      'Verwarm oven op 170 °C, bekleed cakevorm (24 cm) met bakpapier.',
      'Klop zachte boter met suiker 5 min wit en luchtig.',
      'Voeg eieren één voor één toe, blijf kloppen.',
      'Voeg citroenrasp en 40 ml sap toe.',
      'Spatel bloem, bakpoeder en zout er gezeefd door.',
      'Stort in vorm en bak 50-55 min — sateprikker komt schoon uit.',
      'Maak glazuur van poedersuiker + 20 ml citroensap en giet over warme cake.',
      'Laat afkoelen voor je aansnijdt.',
    ],
    baking: '50-55 min op 170 °C.',
  },

  // ─── Koekjes (extra) ─────────────────────────────────────
  {
    id: 'speculaas',
    name: 'Speculaas',
    category: 'Koekjes',
    baseYield: 30,
    yieldUnit: 'koekjes',
    difficulty: 'Makkelijk',
    prepTime: 1500,
    activeLaborMinutes: 30,
    suggestedPackagingCost: 0.05,
    photo: 'https://images.unsplash.com/photo-1607920591413-4ec007e70023?w=600&q=80',
    description:
      'Knapperige Nederlandse koekjes met de typische speculaaskruiden. 24 uur rust geeft de diepste smaak.',
    ingredients: [
      { id: 'sp-1', name: 'Tarwebloem', quantity: 400, unit: 'gram', pricePerUnit: 1.20 },
      { id: 'sp-2', name: 'Bruine suiker', quantity: 250, unit: 'gram', pricePerUnit: 1.50 },
      { id: 'sp-3', name: 'Roomboter (ongezouten)', quantity: 250, unit: 'gram', pricePerUnit: 8.00 },
      { id: 'sp-4', name: 'Heel ei', quantity: 1, unit: 'stuk', pricePerUnit: 0.35 },
      { id: 'sp-5', name: 'Speculaaskruiden', quantity: 15, unit: 'gram', pricePerUnit: 20.00 },
      { id: 'sp-6', name: 'Bakpoeder', quantity: 5, unit: 'gram', pricePerUnit: 6.00 },
      { id: 'sp-7', name: 'Zout', quantity: 3, unit: 'gram', pricePerUnit: 0.80 },
    ],
    instructions: [
      'Meng alle ingrediënten tot een samenhangend deeg (kneed kort).',
      'Wikkel in folie en leg minstens 24 uur in de koelkast (max 3 dagen).',
      'Verwarm oven op 175 °C.',
      'Rol deeg uit tot 4-5 mm dik op met meel bestoven werkblad.',
      'Steek vormen uit of druk in speculaasplank.',
      'Leg op bakplaat met bakpapier.',
      'Bak 12-15 min tot goudbruin.',
      'Laat op rooster afkoelen — wordt knapperig na afkoelen.',
    ],
    baking: '12-15 min op 175 °C. 24 u koelen vóór bakken is essentieel.',
  },
  {
    id: 'chocolate-chip-cookies',
    name: 'Chocolate chip cookies',
    category: 'Koekjes',
    baseYield: 18,
    yieldUnit: 'koekjes',
    difficulty: 'Makkelijk',
    prepTime: 45,
    activeLaborMinutes: 25,
    suggestedPackagingCost: 0.08,
    photo: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=600&q=80',
    description:
      'Amerikaanse klassieker: dik, zacht binnenin, knapperig aan de randen, vol stukken pure chocolade.',
    ingredients: [
      { id: 'cck-1', name: 'Tarwebloem', quantity: 280, unit: 'gram', pricePerUnit: 1.20 },
      { id: 'cck-2', name: 'Roomboter (ongezouten)', quantity: 170, unit: 'gram', pricePerUnit: 8.00 },
      { id: 'cck-3', name: 'Bruine suiker', quantity: 150, unit: 'gram', pricePerUnit: 1.50 },
      { id: 'cck-4', name: 'Kristalsuiker', quantity: 80, unit: 'gram', pricePerUnit: 1.00 },
      { id: 'cck-5', name: 'Heel ei', quantity: 1, unit: 'stuk', pricePerUnit: 0.35 },
      { id: 'cck-6', name: 'Vanille-extract', quantity: 5, unit: 'ml', pricePerUnit: 25.00 },
      { id: 'cck-7', name: 'Bakpoeder', quantity: 5, unit: 'gram', pricePerUnit: 6.00 },
      { id: 'cck-8', name: 'Zout', quantity: 3, unit: 'gram', pricePerUnit: 0.80 },
      { id: 'cck-9', name: 'Pure chocolade (70%)', quantity: 200, unit: 'gram', pricePerUnit: 5.50 },
    ],
    instructions: [
      'Smelt boter tot lichtbruin (beurre noisette). Laat 10 min afkoelen.',
      'Hak chocolade grof in stukken van 1-2 cm.',
      'Klop boter met beide suikers tot glanzend (~2 min).',
      'Voeg ei en vanille toe en klop tot luchtig.',
      'Zeef bloem, bakpoeder en zout erbij en spatel kort door.',
      'Vouw chocolade erdoor.',
      'Vorm bollen (~60 g) en leg ruim uit elkaar op bakpapier.',
      'Bak 11-13 min op 175 °C — randen goudbruin, midden mag nog zacht zijn.',
    ],
    baking: '11-13 min op 175 °C. Niet te lang bakken voor zachte kern.',
  },
]
